Moving over the core Sumologic classes.
drutiny/sumologic pull request #8
Opened 2020-02-01 17:34 UTC by bschilt

2020-02-02 07:30 UTC, fiasco requested changes

2020-02-02 07:30 UTC, fiasco commented on src/Audit/SumoLogicEmptyQuery.php
> +namespace Drutiny\Acquia\CS\Audit;
This needs updating

2020-02-02 07:30 UTC, fiasco commented on src/Audit/SumoLogicQuery.php
> +namespace Drutiny\Acquia\CS\Audit;
Update

2020-02-02 07:30 UTC, fiasco commented on src/Audit/SumologicTimeSeriesGraph.php
> +namespace Drutiny\Acquia\CS\Audit;
Update

2020-02-02 18:51 UTC, bschilt commented
Great catch, @fiasco! Rookie move. I have updated the namespace.

2020-02-09 23:24 UTC, merged

2020-02-09 23:24 UTC, fiasco commented
Thanks Brian!